import subprocess
from pathlib import Path


class GitManager:
    def __init__(self, repo_root: Path):
        self.repo_root = repo_root

    def _run(self, args: list[str], check: bool = True) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git"] + args,
            cwd=str(self.repo_root),
            capture_output=True,
            text=True,
            check=check,
        )

    def create_branch(self, page_id: str) -> str:
        branch = f"migration/{page_id}"
        self._run(["checkout", "-b", branch], check=False)
        return branch

    def checkout_branch(self, branch: str) -> None:
        self._run(["checkout", branch], check=False)

    def commit_step(self, page_id: str, step_number: int, step_name: str, model: str = "", cost: float = 0.0) -> str:
        self._run(["add", "-A"])

        status = self._run(["status", "--porcelain"], check=False)
        if not status.stdout.strip():
            return ""

        feature = page_id.split(".")[-1] if "." in page_id else page_id
        message = (
            f"feat({feature}): step {step_number} - {step_name}\n\n"
            f"Auto-generated by Silicon2 Migration Orchestrator\n"
            f"Page: {page_id}\n"
            f"Model: {model}\n"
            f"Cost: ${cost:.4f}\n"
        )

        result = self._run(["commit", "-m", message], check=False)
        if result.returncode == 0:
            return result.stdout.strip()
        return ""

    def get_current_branch(self) -> str:
        result = self._run(["branch", "--show-current"], check=False)
        return result.stdout.strip()
